spring.application.name=stockmarket

# database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stockmarket}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stockmarket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stockmarket}

# JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# automatically converts camelCase to snake_case
spring.jackson.property-naming-strategy=SNAKE_CASE
