spring.application.name=stockmarket

# database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/stockmarket
spring.datasource.username=stockmarket
spring.datasource.password=stockmarket

# JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
